version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-devops
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    build: .
    container_name: springboot-devops
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_APPLICATION_NAME: Groupe1-2ALINFO4-2425
      SERVER_PORT: 8086
      SERVER_SERVLET_CONTEXT_PATH: /Devops
    ports:
      - "8086:8086"

volumes:
  mysql_data:
